name: 3YearsExperience
favicon: null
layout_spectrum: 0.6914484028238803
typography_spectrum: 0.6283773256000131
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7408476371783763
  lightness: 0.6032872167415917
  saturation: 0.463798392098397
  rhythmicContrast: 0.3157881482038647
purpose: []
